### ISSUE TITLE
On opening map preview a satellite image of Ecuador appears first, before map loads

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/sinangoe-webmap#10]
This may be something left in code from the Waorani map, where we had an image of first map appear whilst the map layers loaded properly. It isn't really appropriate with the current map - or at least the image would need to change if this is a good way of dealing with slow loading layers.

This is image that appears:
<img width="1280" alt="Screenshot 2020-04-29 at 10 53 13" src="https://user-images.githubusercontent.com/21277147/80584857-4038ed00-8a0a-11ea-8c42-c485299cc101.png">

**Comment by okdistribute** [comment]
This should be removed now, but we will likely want to add back a background photo for this map before launch.
