### ISSUE TITLE
Preview not updating / Map not working on scroll

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/sinangoe-webmap#17]
I don't know if this is an issue with my browser storing history or something, but the map preview does not seem to update with the new content (new chapters I have added) and nor does it change  (zoom in and out or move around) when I move between the chapters. 

When I first opened it this morning it was doing the zoom and move - but this has now stopped.

This makes it very hard to work on the maps as I can not preview each chapter's map and check the draft is OK. See zipped video below (this also shows the layer problem from issue #12)  
[bug in CMS scrolling1.mov.zip](https://github.com/digidem/sinangoe-webmap/files/5182895/bug.in.CMS.scrolling1.mov.zip)

**Comment by okdistribute** [comment]
There is an error in the console on the map when I scroll, which shouldn't be happening -- also, though, there might be some inconsistency between the underlying mapbox style and what the CMS is expecting.

**Comment by aliya-ryan** [comment]
Thanks for investigating @okdistribute . @okdistribute @gmaclennan the console error - is that something I fix? and how do we check about the possible inconsistency issue?

**Comment by okdistribute** [comment]
This seems to be fixed now with latest updates, but please feel free to re-open if you continue seeing this issue!
