### ISSUE TITLE
Map preview not updating with new published sections

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/sinangoe-webmap#18]
The map now has 14 chapters / sections. However only the first 6 display - these are the same 6 which displayed when I started work on it yesterday. I have since, yesterday and today, added another 8 sections (with headers and all the. map data, no other content text of photos) but these do not appear in the preview, although they appear as published everywhere on the CMS.

<img width="1440" alt="Screenshot 2020-09-08 at 13 29 28" src="https://user-images.githubusercontent.com/21277147/92477193-12de2600-f1d8-11ea-889f-aeab29bd7153.png">

am looking at the preview here: https://sinangoe-map.ddem.us/

**Comment by okdistribute** [comment]
This should be fixed now, it was failing because it would refuse to render at all if just one of the sections had no content in it. Now, that section will just be empty but the rest of the sections will show.
