### ISSUE TITLE
Header (in tab) of map is wrong

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/sinangoe-webmap#19]
The map still has the 'holder' header in the tab right at the top which was taken from the Wao map which this was copied from (Our Rainforest is not for sale). 

Is there somewhere in the CMS where this can be set - or how is it changed?

For now can it be changed to "Nuestro Territorio es Nuestra Vida" so that it makes more sense when we consult on it?

<img width="724" alt="Screenshot 2020-09-08 at 13 38 19" src="https://user-images.githubusercontent.com/21277147/92477474-95ff7c00-f1d8-11ea-86cd-0e4786c951c9.png">

**Comment by okdistribute** [comment]
This can be changed in `static/index.html`, happy to change it to anything -- we can also make this editable from the CMS but that might take more work than it's worth at this particular moment.
